name: Build and Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test

      - name: Build
        run: |
          npm run build

      # https://github.com/actions/upload-artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: prod-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # https://github.com/actions/download-artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: prod-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
